# Generated by Django 4.1.3 on 2022-11-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=128, verbose_name='имя')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_checked', models.BooleanField(db_index=True, default=False, verbose_name='подтверждение почты')),
                ('web_site', models.CharField(max_length=36, verbose_name='название сайта')),
                ('comment', models.TextField(max_length=254, verbose_name='комментарий')),
                ('photo', models.ImageField(blank=True, default='/unknowing/default.svg', upload_to='comment_photo')),
            ],
        ),
    ]
