# Generated by Django 4.1.3 on 2022-11-29 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='activation_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='comment',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 19, 24, 45, 258330, tzinfo=datetime.timezone.utc)),
        ),
    ]
